export const SET_EMPLOYEE_LIST = "SET_EMPLOYEE_LIST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const USER_LOG_OUT = "USER_LOG_OUT";

export const SET_CHANGE_LOADING = "SET_CHANGE_LOADING";
export const SET_EMPLOYEE_OUTLET_INFO = "SET_EMPLOYEE_OUTLET_INFO";
export const SET_EMPLOYEE_OUTLET_IP = "SET_EMPLOYEE_OUTLET_IP";
export const SET_CHECK_STATUS = "SET_CHECK_STATUS";
export const CHECK_SERVER_RESPONSE = "CHECK_SERVER_RESPONSE";

export const SET_DETAIL_SALARY_INFO = "SET_DETAIL_SALARY_INFO";
export const SET_WORK_SHEET_LIST = "SET_WORK_SHEET_LIST";
export const SET_HISTORY_CHECKIN_LIST = 'SET_HISTORY_CHECKIN_LIST'

export const RESET_WORK_SHEET_LIST = "RESET_WORK_SHEET_LIST";
export const RESET_HISTORY_CHECKIN_LIST = "RESET_HISTORY_CHECKIN_LIST";

export const SET_RESULT_CHECKING_LIST = 'SET_RESULT_CHECKING_LIST'
export const RESET_RESULT_CHECKING_LIST = 'RESET_RESULT_CHECKING_LIST'
export const SET_CHECK_STATUS_LIST = 'SET_CHECK_STATUS_LIST'
export const RESET_USER_CHECKED = 'RESET_USER_CHECKED'

export const RESET_EMPLOYEE_LIST = "RESET_EMPLOYEE_LIST";
