export const SET_EMPLOYEE_LIST = 'SET_EMPLOYEE_LIST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const USER_LOG_OUT = 'USER_LOG_OUT'

export const SET_CHANGE_LOADING = 'SET_CHANGE_LOADING'
export const SET_EMPLOYEE_OUTLET_INFO = 'SET_EMPLOYEE_OUTLET_INFO'
export const SET_EMPLOYEE_OUTLET_IP = 'SET_EMPLOYEE_OUTLET_IP'
export const SET_CHECK_STATUS = 'SET_CHECK_STATUS'

export const RESET_EMPLOYEE_LIST = 'RESET_EMPLOYEE_LIST'
